# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock README.md coze_workflow.py ./

RUN pip install --upgrade pip \
    && pip install "mcp[cli]>=1.5.0" httpx

CMD ["python", "coze_workflow.py"]
